export const FROM_INPUT_CHANGE = '[FROM_INPUT_CHANGE]'
export const TO_INPUT_CHANGE = '[TO_INPUT_CHANGE]'
export const FEE_INPUT_CHANGE = '[FEE_INPUT_CHANGE]'
export const AMOUNT_INPUT_CHANGE = '[AMOUNT_INPUT_CHANGE]'

export const SEND_MESSAGE = '[SEND_MESSAGE]'
export const SEND_MESSAGE_SUCCESS = '[SEND_MESSAGE_SUCCESS]'
export const SEND_MESSAGE_ERROR = '[SEND_MESSAGE_ERROR]'